### PR TITLE
Fix texture memory leak

### LINKED ISSUE #138: Memory leak in background-image
In the example where we're toggling background-images, memory can grow significantly (discovered when working on HDR textures) by pulling in a giant texture and computing it when swapping out background images. This caused my laptop to hang a few times yesterday until tracking it down.

### PR DESCRIPTION
**Pull request by jsantell**
Convert TextureUtils to TextureManager such that the renderer owns themanager so new texture helper instances do not need to be created, and properly dispose of textures that are no longer being used. Fixes #138, memory leak introduced by textures.

### CODE REVIEW

File: src/three-components/TextureManager.js [hunk 1]
```diff
@@ -0,0 +1,107 @@
...
+   */
+  constructor(renderer, config) {
+    super();
+    this.config = Object.assign(
+        {},
+        {
+          cubemapSize: 1024,
+          synthesizedEnvmapSize: 512,
+        },
+        config);
```
Comment (cdata) [inline src/three-components/TextureManager.js]:
```javascript
const defaultConfig = { cubemapSize: 1024, synthesizedEnvmapSize: 512 };
// ...
constructor(renderer, config = {}) {
  this.config = { ...defaultConfig, ...config }
}
```

File: src/three-components/TextureManager.js [hunk 2]
```diff
@@ -0,0 +1,107 @@
...
+    this.cubemapGenerator = new EquirectangularToCubemap(this.renderer);
+    this.envMapGenerator = new EnvMapGenerator(this.renderer);
+  }
+
+  /**
+   * @param {string} url
+   * @return {Promise<THREE.Texture>}
+   */
+  load(url) {
+    return new Promise((res, rej) => loader.load(url, res, undefined, rej));
```
Comment (cdata) [inline src/three-components/TextureManager.js]: Prefer readability over abbreviations

File: src/three-components/TextureManager.js [hunk 3]
```diff
@@ -0,0 +1,107 @@
...
+ * limitations under the License.
+ */
+
+import {TextureLoader, EventDispatcher} from 'three';
+import EquirectangularToCubemap from '../third_party/three.equirectangular-to-cubemap/EquirectangularToCubemap.js';
+import EnvMapGenerator from './EnvMapGenerator.js';
+
+const loader = new TextureLoader();
+
+export default class TextureManager extends EventDispatcher {
```
Comment (cdata) [inline src/three-components/TextureManager.js]: Naming nit: I expect a manager to actually manage its namesake. This class doesn't seem to manage textures, but rather seems scoped to texture conversion. The name "manager" would seem more appropriate if the TextureManager also handled disposing of the textures it generates at the appropriate time, but it doesn't seem to do that.

File: src/three-components/Renderer.js [hunk 4]
```diff
@@ -58,6 +59,7 @@ export default class Renderer extends EventDispatcher {
     this.renderer.gammaFactor = GAMMA_FACTOR;
 
     this[$arRenderer] = ARRenderer.fromInlineRenderer(this);
+    this.textureManager = new TextureManager(this.renderer);
```
Comment (cdata) [inline src/three-components/Renderer.js]: This seems orthogonal to the `renderer` in all ways but lifetime. And the `renderer` is never disposed in practice (is that correct? should it be disposed under some set of circumstances?), so the texture manager won't be either.

What I'm driving at: is the texture manager relevant to the `renderer`, or the `environment` feature? Does it belong here?

File: src/three-components/TextureManager.js [hunk 5]
```diff
@@ -0,0 +1,107 @@
...
+  }
+
+  /**
+   * Returns a { equirect, cubemap } object with the textures
+   * accordingly, or null if cannot generate a texture from
+   * the URL.
+   *
+   * @see equirectangularToCubemap with regard to the THREE types.
+   * @param {string} url
+   * @return {Promise<Object>}
```
Comment (cdata) [inline src/three-components/TextureManager.js]: Can also resolve to `null`

File: src/three-components/TextureManager.js [hunk 6]
```diff
@@ -0,0 +1,107 @@
...
+
+  /**
+   * The texture returned here is from a WebGLRenderCubeTarget,
+   * which is not the same as a THREE.CubeTexture, and just what
+   * the current THREE.CubeCamera uses, and has the same effect
+   * when being used as an environment map.
+   *
+   * @param {THREE.Texture} texture
+   * @param {?number} size
+   * @return {THREE.Texture}
```
Comment (cdata) [inline src/three-components/TextureManager.js]: Is this `@return` annotation accurate?

File: src/three-components/TextureManager.js (hunk 1 above)
Comment (jsantell) [reply src/three-components/TextureManager.js]: :+1:

File: src/three-components/TextureManager.js (hunk 2 above)
Comment (jsantell) [reply src/three-components/TextureManager.js]: :+1:

File: src/three-components/TextureManager.js (hunk 3 above)
Comment (jsantell) [reply src/three-components/TextureManager.js]: Agreed -- unfortunately due to how textures work, it'd be difficult to manage their lifetimes here while giving out textures -- there could be a solution in the future where we have our own texture class that allows individual subscribers to relinquish the texture, and only after all consumers have relinquished does it actually dispose (if we were sharing resources).

TextureGenerator?

File: src/three-components/Renderer.js (hunk 4 above)
Comment (jsantell) [reply src/three-components/Renderer.js]: Correct, renderer is never disposed currently since all elements use the same renderer. We need one TextureGenerator-thing per Renderer, and textures, dispose-wise, are only used and GPU-cached for every WebGLRenderer that uses them

File: src/three-components/TextureManager.js (hunk 6 above)
Comment (jsantell) [reply src/three-components/TextureManager.js]: yeah (explained via proceeding text)

File: src/three-components/TextureManager.js (hunk 3 above)
Comment (cdata) [reply src/three-components/TextureManager.js]: WFM

File: src/three-components/Renderer.js (hunk 4 above)
Comment (cdata) [reply src/three-components/Renderer.js]: We can split these concepts out later
