### PR TITLE
Animations

### LINKED ISSUE #371: Failure to render glTFs with animations
`<model-viewer>` cannot render the [Khronos Brain Stem sample glTF](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/BrainStem). It fails with the following exception before anything is drawn:

image

The failure is on a call to update the model's skeleton: `object.skeleton.update();`.

Notably, this is a sample model with a built-in animation.

This bug was discovered while pursuing #360

### LINKED ISSUE #404: Enable user to configure currently active animation
As we attend #371 , we should consider what it would take to enable users to actively configure the animation that is currently playing.

The most basic level of support would be to add an attribute that enables the user to select the currently playing animation by name.

### PR DESCRIPTION
**Pull request by cdata**
# Animations

This change proposes the addition of new API (and related bug fixes) to configure and present animated glTFs with `<model-viewer>`. Morph, skeletal and keyframe should all be supported.

New public API introduced by this change:

Attribute                      | Default value | Description
------------------------------ | ------------- | ---------------------
`autoplay`&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                        | `false`       | If true, animations will play. Otherwise, they will be stopped. Playing animations will be reset if `animated` changes to false.
`animation-name`               | `undefined`   | If set, `<model-viewer>` will look for an animation with this name when played. If an animation with that name is found, plays that animation. Otherwise, if an animation with that name is _not_ found, falls back to the first animation (if any). |
`animation-crossfade-duration` | `300`         | The duration of the crossfade between animations when changing them via `animation-name`.

Property              | Default value | Description
--------------------- | ------------- | ---------------------
`availableAnimations` | `[]`          | After a model finishes loading, if that model has any animations, they will be listed by string name in this property's value.
`paused`                      | `true`      | Readonly, reflects the play/pause state of the `<model-viewer>`. A `<model-viewer>` displaying a model with no animations is _always_ considered paused.
`currentTime`              | `0`           | This read/write property represents the current track time (in seconds) of the currently playing animation (if any). If a value is assigned, the animation will seek to the time specified.

Method           | Description
------------- | ------------
`play()`          | Plays the animation (selected by `animation-name`, or else falling back to the first animation) if it is available.
`pause()`       | Pauses any currently playing animation

Event               | Description
------------------- | ------------
`pause`                 | Dispatched when the `<model-viewer>` is paused. The implicit default state of `<model-viewer>` is paused, and a `pause` event will not be dispatched until the `<model-viewer>` has been played at least once.
`play`                    | Dispatched when the `<model-viewer>` begins playing animations.
`poster-visibility` | This event is fired when the visibility of the poster image changes. The current visibility state can be read from the `event.detail.visible` property

## Additional highlights

 - Various bugfixes and associated tests to handle race conditions related to changing the `src` attribute quickly
 - A new section has been added to our documentation site: "Animations"
 - Poster image positioning has been changed so that the image is centered within the bounding rect of the `<model-viewer>`
 - A patch that I wrote a while back to correctly clone parsed glTFs w/ animations has been updated and integrated here. This will be necessary until https://github.com/mrdoob/three.js/issues/5878 and https://github.com/mrdoob/three.js/issues/11574 are addressed in Three.js
 - Test timeouts have been increased to 45s because iOS and IE11 are buckling under the strain at this point. Filed #433 to track.

## Examples

`autoplay` | `animation-name="Run"` | Switching `animationName` on an interval
----------- | -------------------------- | ------------------------------------------
animated | animation-name | switch-animation-name

Animated model, in paused state | Switch `animation-name` while paused
--------------------------------- | -------------------------------
 | pauseswitch

 

## Future work

 - Configurable iteration count: https://github.com/GoogleWebComponents/model-viewer/issues/424
 - Built-in default, customizable UI: https://github.com/GoogleWebComponents/model-viewer/issues/425

Fixes #404 
Fixes #371

### CODE REVIEW

File: src/three-components/CachingGLTFLoader.js [hunk 1]
```diff
@@ -35,9 +36,10 @@ export class CachingGLTFLoader {
       cache.set(url, loadWithLoader(url, this.loader));
     }
 
-    const gltf = await cache.get(url);
+    const gltf = cloneGltf(await cache.get(url));
+    const model = gltf.scene ? gltf.scene : null;
```
Comment (mrdoob) [inline src/three-components/CachingGLTFLoader.js]: Wouldn't this turn into `null.userData.animations =` a couple of lines down?

Comment (cdata) [reply src/three-components/CachingGLTFLoader.js]: 👍 Will fix

File: examples/assets/attributions.md [hunk 2]
```diff
@@ -31,6 +31,12 @@ licensed under <a href="https://hdrihaven.com/p/license.php">CC0</a>
 (<a href="https://hdrihaven.com/hdri/?h=whipple_creek_regional_park_04">source</a>)
 Originally in HDR format
 
+## RobotExpressive
+
+RobotExpressive by <a href="https://www.patreon.com/quaternius">Tomás Laulhé</a>,
+licensed under <a href="https://creativecommons.org/publicdomain/zero/1.0/">CC0</a>
+(<a href="https://github.com/mrdoob/three.js/tree/dev/examples/models/gltf/RobotExpressive">source</a>)
+
 ## small_hangar_01
```
Comment (jsantell) [inline examples/assets/attributions.md]: Horse.glb needs attribution

File: index.html [hunk 3]
```diff
@@ -149,6 +153,27 @@ <h4>src<a href="#required-for-display">*</a></h4>
             <h4>alt</h4>
             <p>Configures the model with custom text that will be used to describe the model to viewers who use a screen reader or otherwise depend on additional semantic context to understand what they are viewing.</p>
           </li>
+          <li>
+            <h4>animated</h4>
```
Comment (jsantell) [inline index.html]: I think `animate` might be a better attribute name than `animated` (present vs past tense), although can't think of good prior art (other than "checked", which is past tense, but seems like a different case?)

File: src/features/animation.ts [hunk 4]
```diff
@@ -0,0 +1,171 @@
...
+const $modelLoads = Symbol('modelLoads');
+const $rejectModelLoads = Symbol('rejectModelLoads');
+
+export const AnimationMixin =
+    (ModelViewerElement: Constructor<ModelViewerElementBase>):
+        Constructor<ModelViewerElementBase> => {
+          class AnimationModelViewerElement extends ModelViewerElement {
+            @property({type: Boolean}) animated: boolean = false;
+            @property({type: Boolean, attribute: 'pause-animation'})
+            pauseAnimation: boolean = false;
```
Comment (jsantell) [inline src/features/animation.ts]: `pause-animation` seems unused/undocumented (other than in the scenario where it's checked with !animated), is this necessary?

File: src/features/animation.ts [hunk 5]
```diff
@@ -0,0 +1,171 @@
...
+              return [];
+            }
+
+            /**
+             * Creates a promise that resolves when a model is loaded. The
+             * promise resolves immediately if there is currently a loaded
+             * model. The promise rejects if the currently loaded model is
+             * changed to something new due to the src attribute changing.
+             */
+            [$updateModelLoadsPromise]() {
```
Comment (jsantell) [inline src/features/animation.ts]: Environments has a similar need/way of doing this -- wonder if there's a way to generalize this across all features?

File: src/features/animation.ts (hunk 4 above)
Comment (jsantell) [reply src/features/animation.ts]: Instead of `pause-animation`, there does seem like there would be a need to reset back to the default/T-Pose, so there is a difference between 'pausing' the animation (freezing in the middle of an animation) as opposed to 'removing' the animation -- of course, I don't think it necessary to solve this in this PR

File: src/model-viewer-base.js [hunk 6]
```diff
@@ -189,10 +189,17 @@ export default class ModelViewerElementBase extends UpdatingElement {
...
-  update(changedProperties) {
-    super.update(changedProperties);
+  updated(changedProperties) {
+    super.updated(changedProperties);
 
-    this[$updateSource]();
+    // NOTE(cdata): If a property changes from values A -> B -> A in the space
+    // of a microtask, LitElement/UpdatingElement will notify of a change even
+    // though the value has effectively not changed, so we need to check to make
+    // sure that the value has actually changed before changing the loaded flag.
```
Comment (jsantell) [inline src/model-viewer-base.js]: This seems like it'd be valuable for all properties, not just `src`

File: src/features/loading.js [hunk 7]
```diff
@@ -53,18 +56,19 @@ export const LoadingMixin = (ModelViewerElement) => {
     }
 
     get loaded() {
-      return super.loaded || this[$preloaded];
+      return super.loaded ||
+          (this.src && CachingGLTFLoader.hasFinishedLoading(this.src));
```
Comment (jsantell) [inline src/features/loading.js]: This method, while probably valuable for tests at least, seems that it'd be more appropriate to live on `this.src`, our `Model` class (which could just wrap this); `CachingGLTFLoader` is an implementation detail that would benefit from continuing being hidden inside of Model, or at least out of features/*

File: src/three-components/CachingGLTFLoader.js [hunk 8]
```diff
@@ -14,46 +14,71 @@
...
-      cache.set(url, loadWithLoader(url, this.loader));
+      const loadAttempt = loadWithLoader(url, this.loader);
+      loadAttempt
+          .then(() => {
+            preloaded.set(url, true);
+          })
+          .catch(() => {});  // Silently ignore exceptions here, they should be
+                             // caught by the invoking function
+      cache.set(url, loadAttempt);
+      // window.loadAttempt = loadAttempt;
```
Comment (jsantell) [inline src/three-components/CachingGLTFLoader.js]: nit: comments

File: src/features/loading.js [hunk 9]
```diff
@@ -168,51 +197,50 @@ export const LoadingMixin = (ModelViewerElement) => {
...
-      }
+      const preloaded = CachingGLTFLoader.hasFinishedLoading(this.src);
+
+      if (this[$shouldAttemptPreload]) {
+        const detail = {url: this.src};
+
+        if (preloaded) {
+          this.dispatchEvent(new CustomEvent('preload', {detail}));
+        } else {
+          loader.preload(this.src)
```
Comment (jsantell) [inline src/features/loading.js]: nit: prefer await

File: src/three-components/CachingGLTFLoader.js [hunk 10]
```diff
@@ -14,46 +14,71 @@
...
+   */
+  async preload(url) {
     if (!cache.has(url)) {
-      cache.set(url, loadWithLoader(url, this.loader));
+      const loadAttempt = loadWithLoader(url, this.loader);
+      loadAttempt
+          .then(() => {
+            preloaded.set(url, true);
+          })
+          .catch(() => {});  // Silently ignore exceptions here, they should be
```
Comment (jsantell) [inline src/three-components/CachingGLTFLoader.js]: Any reason using `.then` instead of await? This will swallow exceptions as indicated, but how would invoking function catch that if they're not thrown?

File: src/three-components/Model.js [hunk 11]
```diff
@@ -114,11 +123,37 @@ export default class Model extends Object3D {
       return;
     }
 
-    const scene = await this.loader.load(url);
+    // If we have pending work due to a previous source change in progress,
+    // cancel it so that we do not incur a race condition:
+    if (this[$cancelPendingSourceChange] != null) {
```
Comment (jsantell) [inline src/three-components/Model.js]: Similar concept to other features ensuring that the changes are still valid; can that be abstracted so that model can handle it everywhere? No good ideas currently, but this seems like a potential growing source of race conditions throughout features

File: examples/assets/attributions.md (hunk 2 above)
Comment (cdata) [reply examples/assets/attributions.md]: Will fix

File: src/features/animation.ts (hunk 4 above)
Comment (cdata) [reply src/features/animation.ts]: Yes, it is different from stopping the animation. Pause animation is documented, and will be necessary in order to implement @yuinchien 's mocks to spec.

File: src/features/loading.js (hunk 7 above)
Comment (cdata) [reply src/features/loading.js]: I don't know that I agree. `CachingGLTFLoader` was in fact the abstraction that enabled preloading to work in parallel with normal loading via setting `src`. Please offer a more concrete proposal for how you would change this!

File: src/three-components/CachingGLTFLoader.js (hunk 8 above)
Comment (cdata) [reply src/three-components/CachingGLTFLoader.js]: Will fix

File: src/three-components/CachingGLTFLoader.js (hunk 10 above)
Comment (cdata) [reply src/three-components/CachingGLTFLoader.js]: When you invoke `then` or `catch` in a promise, it does not modify the state of a promise in place. The methods return _new_ promise instances that are resolved differently depending on how you invoked them.

We don't cache the "caught" promise. So, `try`/`catch` blocks outside of this scope will still work as expected.

Comment (cdata) [reply src/three-components/CachingGLTFLoader.js]: And yeah, the reason for using `then` is that the asynchronous behavior is preferred.

File: src/three-components/Model.js (hunk 11 above)
Comment (cdata) [reply src/three-components/Model.js]: I disagree, this problem is fairly unique to the consequences of changing the `src`. Let's discuss offline.

File: index.html (hunk 3 above)
Comment (cdata) [reply index.html]: Will fix

File: src/model-viewer-base.js (hunk 6 above)
Comment (cdata) [reply src/model-viewer-base.js]: Possibly, although the consequences of src change side-effects occurring unnecessarily seem particularly severe as they could affect all other features.

File: src/features/loading.js (hunk 9 above)
Comment (cdata) [reply src/features/loading.js]: I'll re-evaluate if this depends on asynchronous code flow

File: src/features/animation.ts (hunk 5 above)
Comment (cdata) [reply src/features/animation.ts]: After offline discussion, I'm looking into whether this is necessary or not.

File: src/three-components/CachingGLTFLoader.js (hunk 10 above)
Comment (cdata) [reply src/three-components/CachingGLTFLoader.js]: As mentioned in https://github.com/GoogleWebComponents/model-viewer/pull/421#discussion_r265739701 I'll re-evaluate if this is necessary.

File: src/features/animation.ts (hunk 4 above)
Comment (cdata) [reply src/features/animation.ts]: I think the effect you are describing is achieved when setting `animate` to false. Did you have something else in mind?

File: index.html (hunk 3 above)
Comment (cdata) [reply index.html]: Ugh, I forgot: I originally used `animate`, but it's a built-in method of HTMLElement (part of the Web Animations API).

Comment (cdata) [reply index.html]: (and yah that's definitely not going to be confusing for folks _at all_)

😩

File: examples/assets/attributions.md (hunk 2 above)
Comment (cdata) [reply examples/assets/attributions.md]: Attribution added

File: index.html (hunk 3 above)
Comment (cdata) [reply index.html]: This has been left as is, but if there is another name we like that doesn't overlap with a built-in API, I am open to changing it.

File: src/features/animation.ts (hunk 4 above)
Comment (cdata) [reply src/features/animation.ts]: `pause-animation` was not adequately documented, sorry. I added docs for it.

File: src/features/animation.ts (hunk 5 above)
Comment (cdata) [reply src/features/animation.ts]: I reduced the complexity of this implementation substantially, and I _think_ it should be fine. Thanks for calling this out!

File: src/features/loading.js (hunk 7 above)
Comment (cdata) [reply src/features/loading.js]: Keeping this as-is, but remain open to suggestions. I don't think it's the right answer to conflate preloading and the implementation in the `Model` class, because untangling that is what begot `CachingGLTFLoader` in the first place.

File: src/three-components/CachingGLTFLoader.js (hunk 8 above)
Comment (cdata) [reply src/three-components/CachingGLTFLoader.js]: Fixed

File: src/features/loading.js (hunk 9 above)
Comment (cdata) [reply src/features/loading.js]: I factored this out so that it's wrapped in an async function.

File: src/three-components/CachingGLTFLoader.js (hunk 10 above)
Comment (cdata) [reply src/three-components/CachingGLTFLoader.js]: Rewritten with `await`.

File: src/three-components/Model.js (hunk 11 above)
Comment (cdata) [reply src/three-components/Model.js]: After reviewing, I remain convinced that changing the `src` requires special considerations. I'm open to concrete suggestions for refactoring, though.

**Comment by cdata** [comment]
Tests ended in IE11 timeout, flagging for #433

**Comment by mrdoob** [comment]
What about `autoplay` instead of `animated`? Mimicking audio and video tags.

**Comment by cdata** [comment]
`autoplay` is a good idea, I like that.

Although conceptually, we would probably have to introduce an explicit API for pausing + resetting the animation.

For example, to "stop" a `<video>` you have to do something along the lines of:

```javascript
video.pause();
video.currentTime = 0;
```

WDYT? Should we go for something more like that?

I'm also interested to hear what others thing of `autoplay` as a name @jsantell @smalls

File: src/features/animation.ts (hunk 4 above)
Comment (jsantell) [reply src/features/animation.ts]: @cdata yes, with `pause-animation` and `!animate`, both 'freeze' and 'reset' flows are supported

**Comment by smalls** [comment]
I'm good with `autoplay` - in some ways it's not as descriptive (there's no association with an animation), but I think the developer intent is clearer (with `animated`, for instance, it's not clear if it *should* be animated our *could* be animated).

Chris and I chatted about `pause() && currentTime=0` vs `stop()`; I'm fine with the former, and I think that'll give developers extra flexibility. We can always add `stop()` on top of that as a convenience method if needed.

Overall using `<video>` as inspiration for the API makes sense - they've probably thought through some of these issues already.

**Comment by cdata** [comment]
This all SGTM. I'm going to change the current proposal so that the API tracks closely to `<video>`. The bill of changes looks like this in my mind, so please call out if you think any of these changes aren't right:

 - `animated` will become `autoplay`
 - A `pause` method and a `paused` property will be added
    - `pause-animations` attribute/property will be removed
 - `current-time` will be exposed as an attribute/property pair
 - `animation-name`, `availableAnimations` and `animation-crossfade-duration` will remain as-is

**Comment by cdata** [comment]
- API has been overhauled to be more like `<video>` (PR description updated)
 - Additional tests / demo added
 - Docs updated to reflect API change

PTAL at your leisure!

File: src/features/animation.ts (hunk 4 above)
Comment (cdata) [reply src/features/animation.ts]: After API refactor, to "pause" you must invoke `pause()` (there is no corresponding attribute/property). And, to "stop" you subsequently set `.currentTime = 0`.

File: src/three-components/CachingGLTFLoader.js [hunk 12]
```diff
@@ -14,46 +14,72 @@
...
+  async preload(url) {
     if (!cache.has(url)) {
       cache.set(url, loadWithLoader(url, this.loader));
+
+      // loadAttempt
+      //.then(() => {
+      // preloaded.set(url, true);
+      //})
+      //.catch(() => {});  // Silently ignore exceptions here, they should be
+      //// caught by the invoking function
```
Comment (cdata) [inline src/three-components/CachingGLTFLoader.js]: Need to remove

**Comment by mrdoob** [comment]
🎉🎉🎉

**Comment by sowmyy** [comment]
Is there a way to import the array from the gltf file and use it in the component? Because, for me only one of the multiple animations play. rest doesn't! Is this bug already being resolved or yet to ? Also, which is the recommended format for rendering animated 3D models - GLTF or GLB ??
