### PR TITLE
Fix poster a11y

### LINKED ISSUE #905: Default poster element creates accessibility barrier
### Description

The `default-poster` element creates a severe accessibility barrier.

```html
<div id="default-poster" aria-label="This is a 3d Model. Activate to view in 3D!" tabindex="1" style="background-image: url(&quot;https://pathto.com/poster.png&quot;);"></div>
```

Here's the problem:
- `div`: No semantic meaning. Assistive technology will not apply a computed `role` value, therefor the user will not know what this is or how to activate.
- `div`: No default keyboard functionality. There’s no way a screen reader user, sighted keyboard-only user, voice dictation user, etc, can use this.
- `div`: No focus ring. Sighted keyboard users have no visual relaying their current place on the page.
- `div`: Not keyboard focusable, leading to…
- `tabindex=1`: Since a positive value is in use, when the user starts Tabbing through they’ll end up here first, bypassing other content on the page.

The ideal markup would be:
```html
<button type="button" id="default-poster" aria-label="Interact with [item name] 3d model" style="background-image: url(&quot;https://pathto.com/poster.png&quot;);"></button>
```

Now…
- `button`: Has semantic meaning. Assistive technology will apply a computed `role` value of `button`, giving the user notice this will manipulate something on the screen.
- `button`: Features <kbd>Space</kbd> and <kbd>Enter</kbd> default keyboard functionality
- `button`: Provides the user agent default focus ring for sighted keyboard users.
- `button`: Keyboard focusable.
- `tabindex`: No longer required.

#### Live Demo

The markup in question exists in the Glitch demo, but is currently not in use. (Shopify is using this feature which is when I noticed the issue.)
https://model-viewer.glitch.me/

### Browser Affected

- [x] Chrome
- [x] Edge
- [x] Firefox
- [x] Helios
- [x] IE
- [x] Safari

### OS

- [x] Android
- [x] iOS
- [x] Linux
- [x] MacOS
- [x] Windows

### Versions

- model-viewer: v0.7.2

### PR DESCRIPTION
**Pull request by elalish**
Fixes #905 

@svinkle I think I fixed this, but confirmation from someone who knows accessibility better than myself would be great. 

I also took the opportunity to update some three.js methods that were deprecated and were spewing ugly warnings on the console.

### CODE REVIEW

**Comment by cdata** [comment]
Thanks for also fixing those ugly warnings 💯

File: src/template.ts [hunk 1]
```diff
@@ -108,6 +108,7 @@ canvas.show {
   width: 100%;
   height: 100%;
   position: absolute;
+  border: none;
```
Comment (cdata) [inline src/template.ts]: `<button>` has padding by default that we probably want to remove: `padding: 0;`

**Comment by cdata** [comment]
I think we might need to tweak how we adjust `tabIndex` on the element as well. Currently, [we add a `tabindex`](https://github.com/GoogleWebComponents/model-viewer/blob/028176b90006a90595b67f77a2d094c85a684113/src/features/loading.ts#L345) to make the `<div>` focusable, but `<button>` has implicit focusability and does not require this. On the flip side, [we also remove the attribute in an attempt to remove the poster from focus traversal](https://github.com/GoogleWebComponents/model-viewer/blob/028176b90006a90595b67f77a2d094c85a684113/src/features/loading.ts#L383).

I'm not totally sure what the ideal approach to hiding the poster should be, but one option is to set `tabindex` to `-1`, which retains focusability but removes the element from the focus traversal order when tabbing.

@svinkle do you have any suggestions here?

File: src/template.ts [hunk 2]
```diff
@@ -262,7 +264,7 @@ canvas.show {
         will have their <slot> elements removed by ShadyCSS -->
   <div class="slot poster">
     <slot name="poster">
-      <div id="default-poster" aria-hidden="true" aria-label="Activate to view in 3D!"></div>
+      <button type="button" id="default-poster" aria-hidden="true" aria-label="Activate to view in 3D!"></button>
```
Comment (svinkle) [inline src/template.ts]: `aria-hidden="true"` hides this element from assistive technology (yet the tab-stop remains.) Please remove the `aria-hidden` attribute.

Comment (cdata) [reply src/template.ts]: @svinkle the poster starts out in a hidden state unless the user configures it to be visible. If we don't do this, then it is always possible for the user to tab through the poster even when it is not configured or otherwise visible.

**Comment by svinkle** [comment]
There's a few ways to approach this:

- Remove from DOM completely
  ```js
  defaultPosterElement.remove();
  ```
- Hide using `hidden` attribute
  ```js
  defaultPosterElement.hidden = true;
  ```
- Adjust some attributes
  ```js
  defaultPosterElement.setAttribute('aria-hidden', 'true');
  defaultPosterElement.setAttribute('tabindex', -1);
  ```
- Hide using CSS `display: none`

Each will remove the element from all users and assistive technology.

The other question to this process is once the poster is activate and removed, how is keyboard focus managed? Ideally since the poster is used to "reveal" the 3D model, focus would shift to the `canvas` element. From this point the user will hear the announcement of the 3d model when it receives focus and can proceed with interacting with the model. This would also provide confirmation of a successful poster click event.

File: src/template.ts (hunk 2 above)
Comment (svinkle) [reply src/template.ts]: @cdata Got it. Noticed this when reading through [`$showPoster()`](https://github.com/GoogleWebComponents/model-viewer/blob/028176b90006a90595b67f77a2d094c85a684113/src/features/loading.ts#L346).

**Comment by cdata** [comment]
Thanks for the feedback @svinkle ! To your question about poster focus, we do indeed already forward focus to the `<canvas>` once the poster is activated.

I have updated this PR to swap the previous tabindex logic.
