### PR TITLE
Switch environment generation from HalfFloat to RGBE

### LINKED ISSUE #574: Environment map generation fails on some devices
### Description

Model looks very different on different devices. 

On an Android, Honor 7X, it looks like this:
signal-2019-05-28-141018

On iPhone XR:
IMG_5890

On Android, Xiaomi Mi 9:
Screenshot_2019-05-28-17-41-26-090_com android chrome

The last two are pretty similar but reflections still look different (not very visible in the screenshots).

#### Live Demo
https://bramble-geranium.glitch.me/

### Browser Affected

- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [x] Safari

### OS

- [x] Android
- [x] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

Devices where this is broken:

Honor 7X (BND-L21)
Android 8.0
Chrome 74.0.3729.157

Samsung Galaxy S6 (SM-G920F)
Android 7.0
Chrome 74.0.3729.157

### PR DESCRIPTION
**Pull request by elalish**
Fixes #574 

Several major Samsung devices don't support halfFloat textures, causing our environment generation to fail. Switching to RGBE fixes this, but kills our current shader for blurring that environment, so I've created a new gaussianBlur filter for cubeMaps to replace it.

### CODE REVIEW

**Comment by elalish** [comment]
IE 11 says it can't compile a shader, but I can't get it to run on an interactive Sauce Labs session at all (seems to just hang).

File: src/test/three-components/TextureUtils-spec.ts [hunk 1]
```diff
@@ -30,16 +30,14 @@ const HDR_EQUI_URL = assetPath('spruit_sunrise_2k.hdr');
 
 suite('TextureUtils', () => {
   let textureUtils: TextureUtils;
-  let renderer: WebGLRenderer;
+  const renderer = new WebGLRenderer({canvas});
```
Comment (cdata) [inline src/test/three-components/TextureUtils-spec.ts]: We should leave a note here, because `WebGLRenderer` is stateful and can lead to unexpected results in tests depending on the order they are run in down the road.

File: src/three-components/TextureUtils.ts [hunk 2]
```diff
@@ -260,6 +254,115 @@ export default class TextureUtils extends EventDispatcher {
...
+
+    const geometry = new BoxBufferGeometry();
+    geometry.removeAttribute('uv');
+
+    const cubeResolution = cubeTarget.width;
+    const standardDeviations = 3;
+    const n = Math.ceil(
+        standardDeviations * standardDeviationRadians * cubeResolution * 2 /
+        Math.PI);
+    const norm = standardDeviations / ((n - 1) * Math.sqrt(2 * Math.PI));
```
Comment (cdata) [inline src/three-components/TextureUtils.ts]: [Please avoid abbreviations](https://github.com/GoogleWebComponents/model-viewer/wiki/Code-conventions#naming)

File: src/three-components/TextureUtils.ts [hunk 3]
```diff
@@ -260,6 +254,115 @@ export default class TextureUtils extends EventDispatcher {
...
+        void main() {
+          vWorldDirection = transformDirection( position, modelMatrix );
+          #include <begin_vertex>
+          #include <project_vertex>
+          gl_Position.z = gl_Position.w;
+        }
+      `,
+      fragmentShader: [
+        'const float n = ' + n + '.0;',
+        'uniform float weights[' + n + '];',
```
Comment (cdata) [inline src/three-components/TextureUtils.ts]: A couple of comments...

JavaScript numbers have a [`toFixed`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed) method that would probably be appropriate here.

You can also interpolate values with the template string (the one that uses the ` character as its boundary) that follows. For example:

```typescript
const myProgram = `
const float n = ${n.toFixed(1)};
uniform float weights[${n}];

// rest of the program follows ...
`;
```

Template strings are also multi-line friendly, so this will save you from the cumbersome and less legible `.join('\n')` on an array of strings.

File: src/three-components/TextureUtils.ts [hunk 4]
```diff
@@ -260,6 +254,115 @@ export default class TextureUtils extends EventDispatcher {
     }
   }
 
+  gaussianBlur(
```
Comment (cdata) [inline src/three-components/TextureUtils.ts]: 💎

File: src/three-components/TextureUtils.ts [hunk 5]
```diff
@@ -222,6 +215,7 @@ export default class TextureUtils extends EventDispatcher {
             this.environmentMapGenerator =
                 new EnvironmentMapGenerator(this.renderer);
             environmentMap = this.environmentMapGenerator.generate();
+            this.gaussianBlur(environmentMap);
```
Comment (cdata) [inline src/three-components/TextureUtils.ts]: 👍

File: src/three-components/TextureUtils.ts [hunk 6]
```diff
@@ -260,6 +254,115 @@ export default class TextureUtils extends EventDispatcher {
...
+        standardDeviations * standardDeviationRadians * cubeResolution * 2 /
+        Math.PI);
+    const norm = standardDeviations / ((n - 1) * Math.sqrt(2 * Math.PI));
+    let weights = [];
+    for (let i = 0; i < n; ++i) {
+      const x = standardDeviations * i / (n - 1);
+      weights.push(norm * Math.exp(-x * x / 2));
+    }
+
+    const blurMaterial = new ShaderMaterial({
```
Comment (cdata) [inline src/three-components/TextureUtils.ts]: If we make the `blurMaterial` and `blurCamera` class members, we could probably re-use them and then dispose them when `TextureUtils` dispose is called.

Comment (elalish) [reply src/three-components/TextureUtils.ts]: Actually we can't reuse blurMaterial because if you call the function with a different standard deviation, you'll create a different shader. Likewise if you invoke it on a different size texture, you'll have to create a differently sized camera.

Comment (cdata) [reply src/three-components/TextureUtils.ts]: 👍

File: src/test/three-components/TextureUtils-spec.ts (hunk 1 above)
Comment (elalish) [reply src/test/three-components/TextureUtils-spec.ts]: Added.

**Comment by elalish** [comment]
merging this down to the big, combined PR.

**Comment by mrdoob** [comment]
Nice!! 👌👌
