### PR TITLE
Fix progress state thrashing on first configuration

### LINKED ISSUE #847: Loading progress state thrashes on initial configuration
You can see from our progress bar that the reported loading state is thrashing on first load. It jumps from 0 to 1 really fast and then jumps back down to 0 and loads normally. We should fix this to remove the thrashing.

Here is a slowmo GIF of the visual artifact created by the thrashing state:

progressbar

### PR DESCRIPTION
**Pull request by cdata**
When I implemented #833 I introduced the bug described in #847. We did defer loading models as intended, but since `IntersectionObserver` announces intersections somewhat late compared to property updates we were still performing other side-effects early. Among these effects was environment map generation.

With this change, environment map generation is also deferred until we are in the render tree. The rationale for this is that being `display: none` or outside of the viewport should be considered "no cost" in the typical case.

Also, a new, one-time progress activity has been introduced that measures the time before we get the first signal from `IntersectionObserver` that we are visible. This should account for any additional side-effects that measure progress early.

Fixes #847

### CODE REVIEW

File: src/model-viewer-base.ts [hunk 1]
```diff
@@ -211,11 +213,24 @@ export default class ModelViewerElementBase extends UpdatingElement {
...
-            this.requestUpdate();
+            const oldValue = this[$isInRenderTree];
+            this[$isInRenderTree] = this[$scene].isVisible =
+                entry.isIntersecting;
+            this.requestUpdate($isInRenderTree, oldValue);
+
+            if (this[$isInRenderTree]) {
+              // Wait a microtask to give other properties a change to respond
+              // to the state change, then resolve progress on entering the
+              // rendre tree:
```
Comment (elalish) [inline src/model-viewer-base.ts]: nit: rendre -> render, change -> chance

File: src/model-viewer-base.ts [hunk 2]
```diff
@@ -211,11 +213,24 @@ export default class ModelViewerElementBase extends UpdatingElement {
...
     if (HAS_INTERSECTION_OBSERVER) {
+      const enterRenderTreeProgress = this[$progressTracker].beginActivity();
+
       this[$intersectionObserver] = new IntersectionObserver(entries => {
         for (let entry of entries) {
           if (entry.target === this) {
-            this[$scene].isVisible = entry.isIntersecting;
-            this.requestUpdate();
+            const oldValue = this[$isInRenderTree];
+            this[$isInRenderTree] = this[$scene].isVisible =
```
Comment (elalish) [inline src/model-viewer-base.ts]: Can we remove this[$scene].isVisible? It seems to be duplicate.

File: src/test/features/environment-spec.ts [hunk 3]
```diff
@@ -163,6 +163,20 @@ suite('ModelViewerElementBase with EnvironmentMixin', () => {
...
+    const environmentChangeHandler = () => environmentChangeCount++;
+    element.addEventListener('environment-change', environmentChangeHandler);
+    element.style.display = 'none';
+    document.body.appendChild(element);
+    await rafPasses();
+    expect(environmentChangeCount).to.be.equal(0);
+    element.style.display = 'block';
+    await waitForEvent(element, 'environment-change');
+    expect(environmentChangeCount).to.be.equal(1);
+    element.addEventListener('environment-change', environmentChangeHandler);
```
Comment (elalish) [inline src/test/features/environment-spec.ts]: What does this extra addEventListener do?

Comment (cdata) [reply src/test/features/environment-spec.ts]: Sorry, typo. Fixed.

File: src/model-viewer-base.ts (hunk 2 above)
Comment (cdata) [reply src/model-viewer-base.ts]: No, I think it should stay. The reason why is that it controls the notion of visibility on the Three.js side, while `$isInRenderTree` is a detail of the DOM element. If we relied only `$isInRenderTree`, we would be building-in more dependencies on a DOM node in `Renderer`. And then, when we try to move Three.js stuff into a Worker, we have more work to separate those things back out.

File: src/model-viewer-base.ts (hunk 1 above)
Comment (cdata) [reply src/model-viewer-base.ts]: Done

File: src/model-viewer-base.ts (hunk 2 above)
Comment (elalish) [reply src/model-viewer-base.ts]: Fair, but ModelScene extends Scene, which already has a visible member. Can we just use that instead of creating isVisible on top of it? Or do they still have separate meanings?

Comment (cdata) [reply src/model-viewer-base.ts]: That's a good point. My guess is that we can re-use `scene.visible`. I'll look into it.

Comment (cdata) [reply src/model-viewer-base.ts]: Switched over. AFAIK `scene.visible` will always be `true` in the code path where we actually render, so it should be fine.

File: src/test/three-components/Renderer-spec.ts [hunk 4]
```diff
@@ -103,15 +103,15 @@ suite('Renderer', () => {
       expect(!scene.isDirty).to.be.ok;
     });
 
-    test('does not render scenes marked as !isVisible', async function() {
-      scene.isVisible = false;
+    test('does not render scenes marked as not visible', async function() {
```
Comment (elalish) [inline src/test/three-components/Renderer-spec.ts]: This is really just a test of three.js at this point, but I guess it isn't hurting anything.
