### PR TITLE
Fixing skinned mesh cloning

### LINKED ISSUE #790: Skinned glTFs don't render properly
### Description

Some animated models do not render properly, while others do. It seems the ones that fail are skinned meshes.

#### Live Demo
https://googlewebcomponents.github.io/model-viewer/test/fidelity/results-viewer.html
Specifically:
image
and:
image

### PR DESCRIPTION
**Pull request by elalish**
Fixes #790 

Replaced our custom cloning code with the now standard function from Three and fixed a UUID issue with animations.

### CODE REVIEW

File: src/three-components/CachingGLTFLoader.ts [hunk 1]
```diff
@@ -135,11 +135,24 @@ export class CachingGLTFLoader {
...
     await this.preload(url, progressCallback);
 
-    const gltf = cloneGltf(await cache.get(url)!);
-    const model = gltf.scene ? gltf.scene : null;
+    const gltf = await cache.get(url)!;
+
+    if (gltf.scene != null) {
+      // Animations for objects without names target their UUID instead. When
+      // objects are cloned, they get new UUIDs which the animation can't find.
+      // To fix this, we assign their UUID as their name.
```
Comment (cdata) [inline src/three-components/CachingGLTFLoader.ts]: Great comment, thanks!

File: src/three-components/ModelUtils.ts [hunk 2]
```diff
@@ -65,23 +57,10 @@ const updateShader = (shader: Shader) => {
...
-        skinnedMeshes[node.name] = node as SkinnedMesh;
-      }
-    });
-  }
-
-  const cloneBones: BoneMap = {};
-  const cloneSkinnedMeshes: SkinnedMeshMap = {};
+  const clone: Gltf = {
+    ...gltf,
+    scene: hasScene ? SkeletonUtils.clone(gltf.scene!) as Scene : null
```
Comment (cdata) [inline src/three-components/ModelUtils.ts]: 👍
