### PR TITLE
ARRenderer uses EventDispatcher; EventTarget only in tests

### LINKED ISSUE #283: EventTarget usage means master is broken in Safari and IE11
#274 incidentally introduced usage of `EventTarget` without also adding a polyfill, so `<model-viewer>` is currently broken on master for Safari and IE11.

The suggested fix is to change `ARRenderer` to align with `Renderer` by using Three.js's `EventDispatcher` instead.

### PR DESCRIPTION
**Pull request by cdata**
- Changes `ARRenderer` to use `EventDispatcher`
 - Adds the `EventTarget` polyfill for use in test suites.

Fixes #283

### CODE REVIEW

File: src/test/three-components/ARRenderer-spec.js [hunk 1]
```diff
@@ -24,13 +24,15 @@ import {assetPath, timePasses, waitForEvent} from '../helpers.js';
...
-}
+const applyPhoneRotation =
+    camera => {
+      // Rotate 180 degrees on Y (so it's not the default)
+      // and angle 45 degrees towards the ground, like a phone.
+      camera.matrix.identity()
+          .makeRotationAxis(new Vector3(0, 1, 0), Math.PI)
+          .multiply(new Matrix4().makeRotationAxis(
+              new Vector3(1, 0, 0), -Math.PI / 4));
+    }
```
Comment (cdata) [inline src/test/three-components/ARRenderer-spec.js]: Just `clang-format` changes in this file

**Comment by mrdoob** [comment]
Can't wait for [EventDispatcher](https://github.com/mrdoob/eventdispatcher.js/) to become redundant. That'd be one project less to maintain.
