### PR TITLE
Fixed autorotate interpolation

### LINKED ISSUE #806: Model jumps around when camera-target changes
The model jumps around in unexpected ways when changing `cameraTarget`. See the attached screen recording, taken from our deployed docs site.

cameratargetwat

### PR DESCRIPTION
**Pull request by elalish**
Fixes #806 

The first fix was a one-liner to force the pivot to recalculate when the target changes. This caused me to also notice it wasn't smoothly interpolating along with the camera, so I fixed that too.

### CODE REVIEW

File: src/features/controls.ts [hunk 1]
```diff
@@ -302,6 +303,11 @@ export const ControlsMixin = <T extends Constructor<ModelViewerElementBase>>(
       }
 
       this[$controls].update(time, delta);
+      const target = this.getCameraTarget();
+      if (!this[$scene].pivotCenter.equals(target)) {
+        this[$scene].pivotCenter.copy(target);
+        this[$scene].setRotation();
```
Comment (cdata) [inline src/features/controls.ts]: Here we fall back to the argument default, which is tricky to understand without reading the method signature. But, it's equivalent to what we are doing on line 280 because the default we just added is the same value. Let's just drop the default and specify the value here instead.
