### PR TITLE
halfway fixed fidelity capture

### LINKED ISSUE #508: Fidelity tests are broken
### Description

Using npm run check-fidelity results in white images with a progress bar:
Screenshot from 2019-04-26 10-48-51

Sounds like this might be related to #487.

### OS

- [ ] Android
- [ ] iOS
- [x ] Linux
- [ ] MacOS
- [ ] Windows

### Versions
Latest master:
- model-viewer: 0.3.1
- three.js: 0.101.1

### PR DESCRIPTION
**Pull request by elalish**
This is all working now, thanks to hiding the progress bar in the tests. Multi-line find-replace FTW, go VSCode!

### Reference Issue
Fixes #508

### CODE REVIEW

File: src/test/fidelity/artifact-creator.ts [hunk 1]
```diff
@@ -189,7 +189,20 @@ export class ArtifactCreator {
           });
         });
 
-        await Promise.all([modelLoads, environmentChanges]);
+        const modelVisible = new Promise((resolve, reject) => {
+          const timeout = setTimeout(reject, 10000);
+
+          modelViewer.addEventListener('model-visibility', (event) => {
```
Comment (cdata) [inline src/test/fidelity/artifact-creator.ts]: I think we can just replace the `environment-change` event promise with this one. `model-visibility` will only be fired once the model is fully rendered and ready to be revealed, so it implies `environment-change`.

Comment (elalish) [reply src/test/fidelity/artifact-creator.ts]: Sure thing, fixed.

**Comment by cdata** [comment]
Sauce Labs has been killing us lately by randomly failing to start jobs. Gonna go ahead and land this since it looks like it failed to boot up Firefox and my patience for it is low today :)
